version: "2"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: amazon_postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_DB=${POSTGRES_DB:-amazon}
    volumes:
      - .db-data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432